services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    volumes:
      - ./:/var/www/html:cached
      - symfony-var:/var/www/html/var
    depends_on:
      - db
      - mongo

  web:
    image: nginx:1.25-alpine
    ports:
      - "8080:80"                       
    volumes:
      - ./:/var/www/html:cached
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: namaste_test2
      MYSQL_USER: namaste_user
      MYSQL_PASSWORD: mypassword
    volumes:
      - db-data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

  mongo:
    image: mongo:7.0
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - mongo-data:/data/db

volumes:
  symfony-var:
  db-data:
  mongo-data: